# Generated by Django 3.2.20 on 2023-11-12 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='property_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('type_of_property', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20)),
                ('type_of_contract', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000000)])),
                ('rent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250000000)])),
                ('counted_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.city')),
                ('pictures', models.ManyToManyField(blank=True, to='listings.PropertyPicture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='State',
            new_name='Province',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.province'),
        ),
        migrations.AddField(
            model_name='propertypicture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_pictures', to='listings.realestateproperty'),
        ),
    ]
