# Generated by Django 3.2.20 on 2023-11-12 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_auto_20231112_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('type_of_property', models.CharField(choices=[('residental apartment', 'مسکونی آپارتمان'), ('residental villa', 'مسکونی ویلایی'), ('commertial', 'تجاری'), ('industrial', 'صنعتی'), ('agricultural', 'کشاورزی')], max_length=20)),
                ('type_of_contract', models.CharField(choices=[('sale', 'فروشی'), ('rent', 'اجاره'), ('mortgage', 'رهن کامل')], max_length=10)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000000)])),
                ('rent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250000000)])),
                ('counted_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='property_pictures/')),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_pictures', to='listings.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='listings.PropertyPicture'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.province'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.province'),
        ),
    ]
