# Generated by Django 3.2.20 on 2023-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_built_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_properties',
            name='parking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property_properties',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
