# Generated by Django 3.2.20 on 2023-11-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_state_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
    ]
