# Generated by Django 3.2.20 on 2023-11-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_property_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='property_pictures/')),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyPicture',
        ),
    ]
